### ISSUE TITLE
What does the fourth character in this parsing codes signify?

### ISSUE THREAD

**Issue by biblical-text** [byztxt/byzantine-majority-text#10]
There is a S/P in the second last character which appears to represent singular/plural. But the fourth character also has an S/P code. Does anyone know what the first S/P is intended to indicate?

```
hmeterav 2251 {S-1PGSF} 
hmetera  2251 {S-1PNSF}
emouv    1699 {S-1SAPM}
ema      1699 {S-1SAPN}
umeteran 5212 {S-2PASF}
umeterav 5212 {S-2PGSF}
```

Thanks!

**Comment by biblical-text** [comment]
For reference, ἐμοὺς, for example, is tagged with only one S/P pair.

`270220 A- ----APM- ἐμοὺς ἐμοὺς ἐμούς ἐμός`

**Comment by emg** [comment]
Hello

the documentation is here:

https://github.com/byztxt/robinson-documentation/blob/master/doc/DECLINE.COD

To answer your question, here is the relevant paragraph:

    Possessive adjectives have the Person (1,2,3) and number (S,P)
    attached, e.g. S-2PDSM for "umeterw". See "emov", "sov", "hmterov"
    and "umeterov" in the Bagster or Perschbacher lexicon for further
    examples.

Hope this helps.

Best wishes,

Ulrik Sandborg-Petersen
