### ISSUE TITLE
Add missing documentation for BETA version

### ISSUE THREAD

**Issue by emg** [byztxt/byzantine-majority-text#13]
At present, there is not much documentation about the various versions of the text. The documentation available is here:

https://github.com/byztxt/robinson-documentation

The presence of this documentation should be documented inside the byzantine-majority-text repo. Where should this be done? I would think at least in the repo's README.md file. What do you think?

@countingpine recently did some excellent investigative work, and found that the BETA version has some information which appears to be undocumented:

https://github.com/byztxt/byzantine-majority-text/pull/6#issuecomment-1037469417

There, @countingpine wrote:

> I've done a search for " marks, and they appear in three places:
> 
>     Mark 16:8 ("+" [[ "shorter ending" ]])
>     Rom 16:23 (a)delfo/s "+ [14.24-26]").
>     Rev 4:8 (a(/gios "9x")
>
> It looks like the 2005 PDF keeps all three unconverted, so I would say the quotes are supposed to indicate "literal" sections of text.
> 
> I've also found these strings appearing in Revelation: _AX, _DAD, _IB, _KD, _MB, _RMD, _XC. The PDF simply converts these to Greek like everything else, so that might not need any special handling?

Would anyone be interested in documenting any of this?

What documentation format should be used? Probably some form of Markdown is most useful these days?

Where should this documentation live?

**Comment by countingpine** [comment]
Another note: variants appear in the text in the forms:
- `{N - }` (e.g. Mt 17:21)
- `{N [...] > [...] }` (e.g. Mt 17:20)
- `{B [...] > [...] }` (e.g. Mt 11:21)

(`{P}` is the only other use of `{...}`, symbolising paragraph breaks at the start (e.g Mt 1:2) or in the middle (Mt 1:6), and is removed by converter.py.)

(All kinds occur in Matthew, so all my examples all come from there.)

I don't know what the N and B mean, but from the [PDF](https://byzantinetext.com/wp-content/uploads/2016/11/editions-rp-02-matthew.pdf), it looks like N variants appear in footnotes, and B appears in margins.  The majority are `{N ... > ...}`.

Right now, the converter changes the `{N` and `{B` to `{Ν` and `{Β` (capital Nu and Beta).  The result is almost indistinguishable visually, but could cause surprises.

I think if the text were being converted to TeX or some other format for display, these would all be treated as a kind of typesetting markup.

**Comment by countingpine** [comment]
In other news I've made some changes to the code that fix the "quoted text" sections:

https://github.com/countingpine/byzantine-majority-text/commit/quoted

As it stands it's an improvement, but if quoted text sees significant changes in the future (e.g. upper case letters), the code would need some restructuring I think.  I can make a pull request if desired though.

**Comment by normansimonr** [comment]
> I don't know what the N and B mean, but from the [PDF](https://byzantinetext.com/wp-content/uploads/2016/11/editions-rp-02-matthew.pdf), it looks like N variants appear in footnotes, and B appears in margins. The majority are `{N ... > ...}`.

Yeah @countingpine, those are a capital nu and a capital beta. The capital nu means that the text is at variance with the popular Nestle-Aland recension, which is made from a selection of a few ancient papyri with some conjectural adjustments. The capital beta means that there is variation *within* the Byzantine tradition, which encompasses the majority of the corpus and is the one represented in this repository.

> I think if the text were being converted to TeX or some other format for display, these would all be treated as a kind of typesetting markup.

Someone trying to make a LaTeX version of the Byzantine text could benefit from the proposal in #12. Writing an XML to LaTeX converter should not be too complex. At least it should be easier than doing it from the CSVs.
