### ISSUE TITLE
Accents are incorrectly rendered in Unicode version

### ISSUE THREAD

**Issue by normansimonr** [byztxt/byzantine-majority-text#15]
The Unicode text of Heb. 13:3 reads

> Μιμνῃ ́σκεσθε τῶν δεσμίων, ὡς συνδεδεμένοι· τῶν κακουχουμένων, ὡς καὶ αὐτοὶ ὄντες ἐν σώματι.

Notice the accent in Μιμνῃ ́σκεσθε. It should be this instead (image taken from the 2018 Byzantine text PDF):

![Screenshot_20220712_160404](https://user-images.githubusercontent.com/6743349/178595087-c067ba1e-9b28-4c25-9f6b-c49be10fc6bb.png)

A similar problem appears in Heb. 2:6 (μιμνῃ ́σκῃ) and potentially in other passages (where the `ῃ ́` character cluster appears.)

**Comment by emg** [comment]
Well done for spotting this, Norman.

Is this in your code or someone else's?

Is there something I can do to help?

**Comment by normansimonr** [comment]
@emg Thank you! I opened a pull request to fix this! I'm merging it right now.
