### ISSUE TITLE
Wrong character in LU.CCT / 06:38?

### ISSUE THREAD

**Issue by ReneNyffenegger** [byztxt/byzantine-majority-text#2]
I believe the character (^W| in LU.CCT / 06:38 to be wrong.

**Comment by emg** [comment]
Hi Rene

thanks for spotting this.

I believe you are right, this is wrong. The Nestle-Aland text does not have a capitalized omega here. Insted, it says ᾧ here, not ᾯ (U+1FAF). The latter is the code point intended by "(^W|".

I have reported this to Dr. Robinson. He will have the final say over whether the text should be emended.

Many thanks for spotting this.

Best wishes,

Ulrik Sandborg-Petersen

**Comment by emg** [comment]
Hi @ReneNyffenegger 

I checked with Dr. Robinson. He does not think it is an error. His editor style, to be consistent, requires the omega to be a capital omega. That means, the '|' becomes an iota adscript, not subscript, in Unicode code point U+1FAF.

Could you enlighten me on why you believe this to be an error?

Thanks.

Best wishes,

Ulrik Sandborg-Petersen

**Comment by normansimonr** [comment]
Should this issue be closed?

**Comment by ReneNyffenegger** [comment]
I am sorry for not answering your question. I am not sure anymore what caused my concerns about that character in question. So yes, this issue can be closed.

**Comment by emg** [comment]
Many thanks for looking into this, @ReneNyffenegger  – I appreciate your feedback.

Best wishes,

Ulrik
