### ISSUE TITLE
Discrepancies in Unicode files (between accented and non-accented versions)

### ISSUE THREAD

**Issue by githubyouser** [byztxt/byzantine-majority-text#20]
I just realized there's a discrepancy between the accented and non-accented versions of the Unicode CSV files... (This seems to be a consistent problem with words containing μψ.) I've given an example below, but there are several more in Matthew.
### No Accents
[MT.csv - Line 38](https://github.com/byztxt/byzantine-majority-text/blob/master/csv-unicode/no-accents/MT.csv#L38)
2 | 12 | και χρηματισθεντες κατ οναρ μη **_ανακαμθαι_** προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων
### Accents
[MT.csv - Line 38](https://github.com/byztxt/byzantine-majority-text/blob/master/csv-unicode/accents/no-variants/MT.csv#L38)
2 | 12 | Καὶ χρηματισθέντες κατ' ὄναρ μὴ **_ἀνακάμψαι_** πρὸς Ἡρῴδην, δι' ἄλλης ὁδοῦ ἀνεχώρησαν εἰς τὴν χώραν αὐτῶν.

**Comment by normansimonr** [comment]
@githubyouser Thank you so much for reporting this. I am going to delve into this bug this week and keep you posted.

**Comment by githubyouser** [comment]
Sure thing! Thank you so much for making these Unicode versions available for us! I use it all the time. :)

**Comment by normansimonr** [comment]
@githubyouser I just fixed the bug. Thanks so much for reporting it! I also created a new release to reflect the changes, so you may want to download [version 2.0.2](https://github.com/byztxt/byzantine-majority-text) to replace the one you currently have.

Thanks again!
