### ISSUE TITLE
Eph 5:33

### ISSUE THREAD

**Issue by kylak** [byztxt/byzantine-majority-text#27]
Hello,
It seems that there's an error in the morph of φοβῆται in Eph 5:33. It's given 'N' as if it was a deponent but at my knowledges φοβῆται is not deponent. In Eph 5:33 it seems to be the middle voice and should be thus {V-PMS-3S} instead of {V-PNS-3S}.
Gustav.

**Comment by normansimonr** [comment]
Hi @kylak, thanks for opening this issue. I will relay your question to professor Robinson and update you as soon as I hear back from him (note however that Dr. Robinson may not reply straight away).

**Comment by emg** [comment]
@kylak Thanks, Gustav, for this input.

This is a question which only upstream (Dr. Robinson) has the moral right to arbitrate. He is the author, and should have final say. 

@normansimonr - would you consider writing to Dr. Robinson concerning this? Please let me know. 

After checking a few of the authorities  (Thayer (1889); Abbott-Smith (1922); Friberg, Friberg, and Miller (2000), Mounce (1994), Mounce (1993), and Blass-Debrunner-Funk (1961; §387, §389)), and the text itself, I find that the question is slightly difficult to resolve: 

a) FOBE/W is indeed not deponent, according to all four of the lexica consulted. 

b) According the analytical lexica consulted (Mounce, 1993; Friberg, Friberg, and Miller, 2000), it is present passive subjunctive.

c) According to Mounce (1994), "Morphology of Biblical Greek", the middle/passive distinction does not really exist in the present subjunctive for Athematic verbs. According to Mounce, it is better to think of this verb as present middle/passive subjunctive, on analogy with POIH/TAI, from POIE/W - also a contract verb in -E/W, like FOBE/W.

d) According to BDF § 387, and BDF § 389, this is an instance of a I(/NA clause with the present subjunctive functioning like an imperative.

My personal opinion, based on the above, is that the voice should, in this instance, be changed to "Either middle or passive".

@normansimonr you are welcome to include this analysis in your request to Dr. Robinson, if you decide to write to him.


Ulrik Sandborg-Petersen

Bibliography:

Abbott-Smith, George (1922): "A Manual Greek Lexicon of the New Testament", T&T Clark, Edinburgh, London.

Blass, F., Debrunner, A. & Funk, R. (1961): "A Greek Grammar of the New Testament and Other Early Christian Literature: A Translation and Revision of the ninth-tenth German edition incorporating supplementary notes by A. Debrunner, by Robert W. Funk", The University of Chicago Press, Chicago and London.

Friberg, Timothy, Friberg, Barbara, and Miller, Neva F. (2000): "Analytical Lexicon of the Greek New Testament", Baker Books, Grand Rapids, Michigan.

Mounce, William D. (1993): "The Analytical Lexicon to the Greek New Testament", Zondervan Publishing House, Grand Rapids, Michigan.

Mounce, William D. (1994): "The Morphology of Biblical Greek", Zondervan Publishing House, Grand Rapids, Michigan.

Thayer, Jospeh Henry (1889) "Thayer's Greek-English Lexicon of the New Testament", Associated Publishers and Authors, Inc., Grand Rapids, Michigan.

**Comment by normansimonr** [comment]
@emg Thank you so much. I have written to Prof. Robinson and will keep you and Gustav updated.

**Comment by kylak** [comment]
Thanks Ulrik for the verification, and thanks @normansimonr for your help contacting Prof. Robinson.

**Comment by normansimonr** [comment]
I have just heard back from Professor Robinson. I copy his answer below:

> If the M/P form of  φοβεω functions as an active voice in this construction, it can be considered deponent, in which case the PNS designation would be correct ("that the wife should respect") .
>
> Compare Perschbacher, _NT Greek Syntax_, p. 331, who treats this specific form as "3 pers. sing. pres. mid./pass. dep. subj. (imperatival ίνα)".
> 
> The alternative PES designation (either middle or passive) requires more on the part of the reader than is necessary ("that the wife should [for her own benefit] respect" or "that the wife should be respecting"). However, it can remain an equal option as to either PNS or PES, depending on one's interpretation.
> 
> I would therefore leave it as is.
>
> I notice also that Friberg's _Analytical Greek NT_ cites φοβηται here as VSPN-ZS (i.e. verb subjunctive present middle or passive deponent 3sg).

@kylak I hope this helps.

**Comment by kylak** [comment]
Thanks a lot for the answer, but I think that there's an error.

Actually phobeo doesn't mean to respect. **It means to frigthen**, which is seems to be the opposite!

I respect you implies I allow you to be with me, to be part of my life for example. Whereas I frigthen you implies I prefer that you don't stay with me, that you shouldn't be part of my life ; in that sense for example it's the opposite.

The reality is that phobeo doesn't mean at all to respect (accordind to the LSJ dictionnary for example) ...
To respect can (in according to the Bailly dictionnary) be said in ancient greek through the words ὀπίζω, or πολυωρέω for example, but shouldn't be use at my knowledges through phobeo.

"ego phobeo auton" means "Me, I frigthen him." which is completly different than "Me, I respect him" !

So, depending on the meaning that we put on phobeo, yes it could be deponent. But actually when we take the real meaning of the word, it is clear that it's not deponent.

In Eph 5:33 for example, it would give :
- the woman ? that she respects the man (deponent the medio-passive form gives an active sense) [wrong]
- the woman ? that she is frightened of the man (not deponent, the medio-passive form gives a medio-passive sense) [good]

When we choose the real sense of phobeo, it's clear that there's no problem about if it's deponent or not.

I think that the reason why many translations use "to respect" instead of "to frighten" is because of a latin new testament biais, new testament in which we could understand in english "to honor" instead of "to frighten".

The sense of phobeo can be checked in various dictionnaries such as for example the LSJ.

Best regards,
Gustav.

**Comment by normansimonr** [comment]
Thank you, this makes sense. As we are only maintainers of the repository and the only person with the authority to make changes to the text is professor Robinson, I totally hear you but I will have to leave the current parsing as that is what Dr. Robinson has requested.

I think your line of reasoning is attractive, but I agree with professor Robinson in understanding the verb as meaning 'to respect'. My two pennies: the Greek New Testament was heavily influenced by Hebrew and Aramaic, and in those languages there was a not insignificant degree of semantic overlap between the notions of respect and fear, so I totally see Paul using φοβῆται to mean 'to respect/honour', also as in 'not being disrespectful'.

I'm closing the issue, but I appreciate all the opinions shared in this thread. Thank you again for opening it.

**Comment by kylak** [comment]
I've found your comment on the hebrew and aramaic influence very interesting, thanks for the sharing.
Thanks for your hearing.

**Comment by nouveautestament** [comment]
Yes like Erasmus.
But i prefer think like God, and not like this world.
TIMEO in ROMAN
![image](https://github.com/byztxt/byzantine-majority-text/assets/84104408/cf86e5b3-3cb6-491a-906f-d93a5776fa00)
