### ISSUE TITLE
How to explain that ?

### ISSUE THREAD

**Issue by kylak** [byztxt/byzantine-majority-text#35]
In Colossian 1:2, we read in the R.P text "Κολασσαῖς" and not "Κολοσσαῖς" like some others Greek New Testament have.

The problem is that the real form of this noun is, at my knowledge, the omicron version... not the alpha one ...

So how to explain this errror ?

**Comment by normansimonr** [comment]
Hi @kylak, thank you for your comment. As far as I can tell, this is simply a matter of spelling variation. See for instance p. 44 of Winer's [grammar](https://archive.org/details/grammarofidiomof00wine/page/44/mode/1up). See also the entry on p. 252 of the Abbott-Smith [lexicon](https://archive.org/details/manualgreeklexic00abborich/page/252/mode/1up). I am marking this issue as resolved, but feel free to re-open it if you have further questions about the same variant.

Thank you.
