### ISSUE TITLE
Words with multiple parsing codes?

### ISSUE THREAD

**Issue by skosonen** [byztxt/byzantine-majority-text#37]
Why in these couple of verses there are words with two different parsing codes?
Is this an error in the text, or can these words somehow have two parsing codes?

Example:
James 4:5
`...το 3588 {T-NSN} 3588 {T-ASN}...`

Verses to be checked for these:

Matthew 26:45
Matthew 27:9
Mark 14:41
Luke 17:36
John 1:9
John 5:39
John 15:18
John 21:15
Acts 4:9
Acts 8:37
Acts 15:34
Acts 24:7
Romans 8:28
1 Corinthians 2:13
1 Corinthians 7:36
Galatians 3:7
Colossians 3:24
2 Timothy 2:6
Hebrews 13:23
James 2:24
James 4:5
1 Peter 1:6
2 Peter 2:19
1 John 5:1
Revelation 3:17

**Comment by normansimonr** [comment]
@skosonen Thank you very much for reporting this! I'm investigating. I will post here as soon as I have an answer.

**Comment by normansimonr** [comment]
@skosonen Thanks again for your question. As it happens, the double codes are correct. Take [James 4:5](https://github.com/byztxt/byzantine-majority-text/blob/master/source/Strongs/20_JAM.BP5#L76C170-L76C297) for instance

> epipoqei 1971 {V-PAI-3S} to 3588 {T-NSN} 3588 {T-ASN} pneuma 4151 {N-NSN} 4151 {N-ASN} o 3739 {R-ASN} katwkhsen 2730 {V-AAI-3S}

These codes are saying that "to" and "pneuma" could be either nominative or accusative, given that the words are neuter. So whenever you see two codes associated to a single word, that means that, based on the word's morphology, either of the two parsings is applicable.

I hope this makes sense.

Thank you!

**Comment by skosonen** [comment]
Thanks, it makes sense.

**Comment by normansimonr** [comment]
Awesome. I'm marking the issue as resolved then. Cheers!

**Comment by normansimonr** [comment]
@emg Good call. I'm opening an issue to include this in the documentation of the next release.
