### ISSUE TITLE
Conversion to unicode fails with punctuation (variants)

### ISSUE THREAD

**Issue by jcuenod** [byztxt/byzantine-majority-text#5]
https://github.com/byztxt/byzantine-majority-text/blob/6bcbfd664991db05f3b915afafa0b844c5d8a418/csv-unicode/converter.py#L244

I noticed in Jude 5 that the final sigma in "[ὑμᾶσ]" is not being recognised. Presumably because of the punctuation.

> {Ν ὑμᾶς ἅπαξ τοῦτο ὅτι ὁ κύριος > [ὑμᾶσ] πάντα ὅτι [ὁ] κύριος ἅπαξ }

Maybe this should be filed against `beta-code`, though...

**Comment by normansimonr** [comment]
@jcuenod Thanks a lot for spotting this! @emg I am preparing the pull request to fix this. Will update here when done.

**Comment by jcuenod** [comment]
@emg I see you've been active recently, I think the pull request (referenced above) is ready to merge if you're happy with it.

**Comment by emg** [comment]
Thanks, @jcuenod – yes, I am getting back into things. I would like to catch up with you somehow – perhaps Skype or Zoom? Please shoot me an email if that idea seems pleasing to you.

PR #6 has been applied.

I herewith close the issue.

**Comment by normansimonr** [comment]
@emg Oh, actually, Ulrik, I'm adjusting #6 to incorporate @countingpine's comments. We haven't merged #6 yet, so this issue should still be open. What @countingpine did was fix #7 , but #5 is still unresolved. Can you possibly reopen it?

**Comment by emg** [comment]
@normansimonr  – thanks for keeping me straight :-) Sorry, I had missed that one. Thanks for having my back.

Reopening, because that's the way :-).
