### ISSUE TITLE
Revelation 6:9 tan yucan / τὰς ψυχὰς 

### ISSUE THREAD

**Issue by biblical-text** [byztxt/byzantine-majority-text#8]
Regarding Revelation 6:9

`tav 3588 {T-APF} | yucav 5590 | <yucav> 5590 VAR: yucav 5590`

https://github.com/byztxt/byzantine-majority-text/blob/6bcbfd664991db05f3b915afafa0b844c5d8a418/parsed/RE.UB5#L967

https://github.com/byztxt/byzantine-majority-text/blob/6bcbfd664991db05f3b915afafa0b844c5d8a418/textonly-beta-code/RE.CCT#L107

Should it be tan yucan? Maybe it is a typo? The "CNTTS Apparatus" in accordance doesn't list a single manuscript with the ν ending. Does anyone know what is going on here?

**Comment by emg** [comment]
The encoding of the parsed text is not BETA encoding, but (I believe) Online Bible encoding.

In this latter encoding, "v" means "final sigma", not "nu".
