### ISSUE TITLE
Mismatches John 2018 vs. 2021

### ISSUE THREAD

**Issue by Mathias-Hofmann** [byztxt/byzantine-majority-text#9]
Dear Ulrik,
not sure if this is some encoding issue on my end, but when I compared the version 2018 to the current version I found the mismatches below. 

The first issue shows a mismatch regarding the apostrophe "ʼ" vs. "'", the second one concerns the "ϊ" character in combination with an apostrophe. If this is some bug, it is a critical one as it splits a single valid word in two invalid terms.

I only compared JOH.csv.

2018	2021	Verse
----------------------------------------------------
ʼ	'	1.3, 1.7, +142 more
Λευΐτας		Λευϊ ́τας	1,19,
Ἠσαΐας		Ἠσαϊ ́ας		1.23, 12.39, 12.41, 
Ἐφραῒμ		Ἐφραϊ`μ	11.54
βαΐα	βαϊ ́α	12.13
Ἠσαΐου		Ἠσαϊ ́ου	12.38
πρωΐ,	        πρωϊ ́,	18.28, 20.1
Πρωΐας		Πρωϊ ́ας	21.4

These are the only mismatches between the two versions though.

Best regrads,
Mathias

**Comment by countingpine** [comment]
This seems to be the same problem as in #7. It looks like `+/` and `+\` in the beta-code need to be fixed to `/+` and `\+` during the conversion.

**Comment by emg** [comment]
Thanks for contributing the solution, @countingpine. Your work is highly appreciated.

Thanks, @Mathias-Hofmann, for noting this. Thanks for taking the trouble to report it. Your contribution is also appreciated.

**Comment by emg** [comment]
@countingpine Please could I ask you to fix up PR #6 and reapply it. Then I can merge PR #6 also.

@Mathias-Hofmann Please could I ask you to confirm whether @countingpine's good work fixes this issue? I leave it to you to decide whether you want to wait until PR #6 has been merged. Thanks.

Please do keep the contributions coming.

**Comment by normansimonr** [comment]
This seems to have been fixed by #11
